services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: employees_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database:/docker-entrypoint-initdb.d

  php:
    build: ./src
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

volumes:
  mysql_data:
