CREATE DATABASE IF NOT EXISTS EMPLOYEES_DB;

USE EMPLOYEES_DB;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    MARITAL_STATUS ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);